ProjectReckoning/reckoning-mobile-app

app.json
lib/api.js
package-lock.json
package.json
stores/authStore.js
stores/errorStore.js

add base url
add api interceptor for API related error handling
add errorStore
add authStore
add dependencies (expo secure storage)

chore: add global stores

---

app/(auth)/_layout.jsx
app/(auth)/login.jsx
app/(auth)/loginForm.jsx
app/(main)/_layout.jsx
app/(main)/home/index.jsx
app/_layout.jsx
app/index.jsx
lib/api.js
stores/authStore.js
stores/errorStore.js

- add authenthication to BE
- add authorization to routes
- configure base url
- configure zustand and secure storage for authorization
- configure routing for redirections

feat: [TAKUA-154] authentication and authorization integration

---

utils/colorUtils.js

update warna dan ada tambahan warna gray

chore: update warna

---

app/(main)/pocket/[id]/index.jsx
components/common/ReusableRoundedTabBar.jsx
components/common/icons/TravelIconWithBar.jsx
components/common/tableCells/BalanceMemberListCell.jsx
components/common/tableCells/InfoMemberDetailCell.jsx
components/common/tableCells/TransactionHistoryTableCell.jsx
components/common/typography/AppText.jsx
components/common/typography/ResponsiveText.jsx
components/feature/pocketDashboard/PocketDashboardTopBar.jsx
components/feature/pocketDashboard/balance.jsx
components/feature/pocketDashboard/balance/AccountNumber.jsx
components/feature/pocketDashboard/balance/BalanceMemberList.jsx
components/feature/pocketDashboard/balance/CircularProgressBar.jsx
components/feature/pocketDashboard/balance/PaymentDateInfo.jsx
components/feature/pocketDashboard/balance/TransactionButtonGroup.jsx
components/feature/pocketDashboard/history.jsx
components/feature/pocketDashboard/history/HistoryContent.jsx
components/feature/pocketDashboard/history/MonthSelectionBar.jsx
components/feature/pocketDashboard/info.jsx
components/feature/pocketDashboard/information/MemberDetail.jsx
components/feature/pocketDashboard/information/MemberDetailList.jsx
components/feature/pocketDashboard/information/OwnerDetail.jsx
components/feature/pocketDashboard/information/PocketDetail.jsx
stores/pocketStore.js
tailwind.config.js
utils/helperFunction.js
utils/typographyUtils.js

- integration with API (balance, history, info)
- configure global typography utility functions and components (responsive text, variants)
- configure pocketStore to receive and store fetched API data
- refactor every pocket dashboard component to use responsive text, global typography variants, and pocketStore stored data
- removed unnecessary import and comments
- other optimization

feat: [TAKUA-241, 242, 243] pocket dashboard integration + refactor + configs

---

app/(main)/_layout.jsx

- fix navigation button
- fix navigation stack logic

fix: [TAKUA-246] navigation header and navigation stack issues

---

app/(main)/_layout.jsx
app/(main)/pocket/transaction/Confirmation.jsx
app/(main)/pocket/transaction/Detail.jsx
app/(main)/pocket/transaction/PinCode.jsx
app/(main)/pocket/transaction/Statement.jsx
app/(main)/pocket/transaction/topup/index.jsx
app/(main)/pocket/transaction/transfer/index.jsx
app/(main)/pocket/transaction/withdraw/index.jsx
app/index.jsx

- fix the header in transaction folder, adjusted to _layout in (main)

Fix: header in transaction

---

app/(main)/pocket/all/index.jsx
app/index.jsx
stores/pocketStore.js

integrate pocket delete functionality with DELETE /pocket/{id} API

feat: [TAKUA-247] pocket delete integration

---

stores/pocketStore.js

add temporary logging to API call

chore: add temporary logging to API call

---

app/(main)/_layout.jsx
app/(main)/pocket/[id]/transaction/Confirmation.jsx
app/(main)/pocket/[id]/transaction/Detail.jsx
app/(main)/pocket/[id]/transaction/PinCode.jsx
app/(main)/pocket/[id]/transaction/Statement.jsx
app/(main)/pocket/[id]/transaction/topup/index.jsx
app/(main)/pocket/[id]/transaction/transfer/index.jsx
app/(main)/pocket/[id]/transaction/withdraw/index.jsx
components/common/FriendList.jsx
components/feature/pocketDashboard/balance/TransactionButtonGroup.jsx
stores/transactionStore.js

- integrate transaction API into pocket dashboard screen
- POST /pocket/withdrawal
- POST /pocket/topup
- POST /pocket/transfer
- modify pocketStore to store temporary transaction field data

feat: [TAKUA-257,258,259] transaction integration

---

app/(main)/_layout.jsx
app/(main)/pocket/[id]/transaction/Statement.jsx
app/(main)/pocket/create/Customization.jsx
app/(main)/pocket/create/Details.jsx
app/(main)/pocket/create/NewFriend.jsx
app/(main)/pocket/create/NewUser.jsx
app/(main)/pocket/create/NewUserConfirmation.jsx
app/(main)/pocket/create/SelectFriend.jsx
app/(main)/pocket/create/SelectGoal.jsx
app/(main)/pocket/create/index.jsx
components/common/FriendList.jsx
components/feature/createPocket/GoalCard.jsx
components/feature/createPocket/PocketTypeCard.jsx
stores/pocketStore.js
utils/colorUtils.js
utils/mockData/featureData.js

- Add a new receiver in the transfer flow
- Invite new friends to the pocket member
- Fix the layout after apply root header

New Friend in Transfer and Pocket Member Feature

---

app/(main)/_layout.jsx
app/_layout.jsx
components/common/ErrorModal.jsx
hooks/usePushNotifications.js
lib/api.js
lib/notificationService.js
stores/authStore.js
stores/errorStore.js
stores/pocketStore.js
stores/transactionStore.js

setup global error handler for network calls

chore: setup global error handler for network calls

---

app/(main)/pocket/all/index.jsx
components/common/buttons/PrimaryButton.jsx
components/feature/allPocket/EmptyPocket.jsx
components/feature/allPocket/PocketActionSheet.jsx
stores/pocketStore.js

- pocket color & icon in pocketcard, edit modal, delete modal
- filter business pocket
exclude:
- edit pocket

Refactor Preview All Pocket Screen

---

app/(main)/pocket/transaction/autoBudgeting/SetAutoBudgeting.jsx
app/(main)/pocket/transaction/autoBudgeting/autoBudgetingConfirmation.jsx
app/(main)/pocket/transaction/autoBudgeting/index.jsx
components/common/CustomDatePicker/CustomDatePicker.jsx

create auto budgeting screen on boarding - confirmation

feat: [TAKUA-260] auto budgeting screen

---

app/(main)/home/testscreen/index.jsx
app/(main)/pocket/[id]/transferSchedule/index.jsx
app/(main)/pocket/transaction/balance/index.jsx
app/(main)/pocket/transaction/info/index.jsx
app/index.jsx
components/feature/balance/BalanceCategory.jsx

fix balance category component

fix: balance category component

---

components/feature/pocketDashboard/common/SharedPocketButtonGroup.jsx

fix: modal data image source

---

app/(main)/pocket/[id]/index.jsx
app/(main)/pocket/[id]/transaction/autoBudgeting/SetAutoBudgeting.jsx
app/(main)/pocket/[id]/transaction/autoBudgeting/autoBudgetingConfirmation.jsx
app/(main)/pocket/[id]/transaction/setTarget/index.jsx
components/common/buttons/SquaredButton.jsx
components/feature/pocketDashboard/common/SharedPocketButtonGroup.jsx
components/feature/pocketDashboard/common/balance/AccountNumber.jsx
hooks/usePushNotifications.js
package-lock.json
package.json
stores/authStore.js
stores/friendshipStore.js
stores/pocketStore.js
stores/transactionStore.js

- integrate auto budgeting
- integrate set target (spending to saving)
- integrate change target 
- fix API logging
- remove unused logging
- add copy account number functionality
- add toast on trigger copy account number
- bugfixes

feat: auto budgeting and set / change target integration

---

app/(main)/pocket/[id]/index.jsx
app/(main)/pocket/[id]/transaction/PinCode.jsx
app/(main)/pocket/[id]/transaction/Receipt.jsx
app/(main)/pocket/[id]/transaction/Statement.jsx
app/(main)/pocket/[id]/transaction/autoBudgeting/autoBudgetingConfirmation.jsx
components/common/tableCells/TransactionHistoryTableCell.jsx
components/feature/pocketDashboard/common/history/HistoryContent.jsx
stores/pocketStore.js
stores/transactionStore.js

fix transaction store, pocket store, transaction flow

fix: transaction store, pocket store, transaction flow

---

components/common/tableCells/InfoMemberDetailCell.jsx
components/feature/pocketDashboard/common/InfoBalanceContent.jsx
components/feature/pocketDashboard/common/information/MemberDetailList.jsx
components/feature/pocketDashboard/common/information/PocketDetail.jsx
utils/typographyUtils.js

fix: Info screen and modal

---

app/(main)/pocket/create/NewUser.jsx
app/(main)/pocket/create/NewUserConfirmation.jsx
components/common/tableCells/BalanceMemberListCell.jsx
components/common/tableCells/ReusableInformationCell.jsx
components/feature/pocketDashboard/common/balance/BalanceMemberList.jsx
components/feature/pocketDashboard/common/balance/PressableCircle.jsx
stores/friendshipStore.js
stores/notificationStore.js
stores/pocketStore.js

fix add friend integrations, fix balance screen stylings

fix: add friend integrations, fix balance screen stylings

---

app/(main)/pocket/[id]/transaction/Confirmation.jsx
app/(main)/pocket/[id]/transaction/Statement.jsx
components/common/BadgeRole.jsx
components/common/tableCells/InfoMemberDetailCell.jsx
components/common/tableCells/TransactionHistoryTableCell.jsx
components/feature/pocketDashboard/business/businessInformation.jsx
components/feature/pocketDashboard/common/InfoBalanceContent.jsx
components/feature/pocketDashboard/common/information/MemberDetail.jsx
components/feature/pocketDashboard/common/information/MemberDetailList.jsx
components/feature/pocketDashboard/common/information/OwnerDetail.jsx
components/feature/pocketDashboard/common/information/PocketDetail.jsx
components/feature/transferSchedule/SetScheduleTransferContent.jsx

confirmation, statement, info screen,transaction history

fix : confirmation, statement, info screen,transaction history

---

components/feature/notification/NotificationDetailContent.jsx
components/feature/notification/NotificationList.jsx
utils/mockData/modalData.js

integrate notification list and detail, approval in progress

feat: notification integration

---

app/(main)/pocket/[id]/transaction/Confirmation.jsx
app/(main)/pocket/[id]/transaction/Detail.jsx
app/(main)/pocket/[id]/transaction/PinCode.jsx
app/(main)/pocket/[id]/transferSchedule/[_id]/index.jsx
stores/transactionStore.js
utils/mockData/modalData.js

fix transfer flow, transfer schedule, admin approval modal

fix: transfer flow, transfer schedule, admin approval modal

---

components/feature/transaction/CategoryActionsheet.jsx

fix: action sheet scroll view

---

components/common/CustomMonthPicker.jsx
components/feature/transferSchedule/SetScheduleTransferContent.jsx

Fix custom month picker in schedule transfer modal

fix: Custom month picker in schedule transfer modal
